### ISSUE TITLE
Allow commands to be run with a token parameter instead of being logged in

### ISSUE THREAD

**Issue by lukekarrys** [sintaxi/surge#63]
*Feature Request*

I'd like the ability to run commands like `surge --project ./build` without being logged in. Other CLIs do this with some sort of token parameter so the command ends up being  `surge --project ./build --token ABC123`.

This would be helpful when trying to deploy from CI/CD services where you'd want to use your token as an environment variable, and not have to deal with the multistep login process.

**Comment by kennethormandy** [comment]
This makes a lot of sense, thanks for all the details! Is `--token` the most likely name you’d expect for the flag? Also, if you don’t mind me asking, what CI services would you anticipate using this with, just so we can look into any possible nuances?

**Comment by lukekarrys** [comment]
`--token` is what I'd expect, but that's mostly based on using [`divshot-cli`](https://www.npmjs.com/package/divshot-cli) for similar things in the past and that's the name it uses.

I'm using [Codeship](http://codeship.com) currently for CI/CD. They allow for setting environment variables and then using them in deploy scripts like this:

![screen shot 2015-03-05 at 11 01 51 am](https://cloud.githubusercontent.com/assets/542108/6511011/10a85102-c327-11e4-9efb-bb6c743c918d.png)

Also will there need to be commands to create tokens and deauth existing tokens? Or would they just need to be grabbed from the existing `.netrc` file?

**Comment by marvinroger** [comment]
Yes I also need this, CI/CD is so important in a workflow today! I personally use Wercker which uses a wercker.yml file. In the Wercker UI, I can set an environment variable and use it in the deploy script, just like @lukekarrys, this way:

```yaml
box: wercker/nodejs
build:
  steps:
    - npm-install
    - npm-test
    - script:
      name: build
      code: npm run build
    - script:
      name: copy build to the to-be-deployed directory
      code: cp -a ./dist/. $WERCKER_OUTPUT_DIR
deploy:
  steps:
    - script:
      name: push to surge
      code: surge ./ mydomain.com --token $SURGE_TOKEN
```

**Comment by constantx** [comment]
:+1:

**Comment by brandonb927** [comment]
:+1:

**Comment by Rich-Harris** [comment]
Yes, this would be hugely beneficial! I primarily use Travis CI - you encrypt your environment variables locally using `github_username/reponame` as a key and add them to your `.travis.yml` file as `secure` ([example](https://github.com/ractivejs/docs.ractivejs.org/blob/master/.travis.yml)) or [via their UI](http://docs.travis-ci.com/user/environment-variables/#Using-Settings).

`--token` seems as good a name as any.

**Comment by lewiscowper** [comment]
I'm also using Travis CI, `--token` seems as reasonable as any name. This would be the killer feature for me, and would automate my entire workflow from git commit through to deployed.

**Comment by sintaxi** [comment]
I'm in agreement on this. I'll try to get this in one of the next
iterations. Hopefully shortly.

**Comment by callum** [comment]
@kennethormandy didn't see this one, thanks. Seems like most CI providers allow you to privatise environment variables to enable this. I've been looking into Travis and Circle CI. 

Relevant: https://circleci.com/docs/language-nodejs#npm-authentication

I prefer `surge token` over `surge --token`. Feels more consistent with the current API.

An example Circle CI config:

```yml
deployment:
  production:
    branch: production
    commands:
      - NODE_ENV=production npm run build
      - surge example.com
  staging:
    branch: master
    commands:
      - NODE_ENV=staging npm run build
      - surge staging.example.com
```

**Comment by kennethormandy** [comment]
Hey everyone!

Thanks to your feedback, you can now use environment variables and display your token ✨

![](https://surge.sh/images/help/integrating-with-travis-ci.gif)

🎓Update to the latest version of the Surge CLI by running:

```
npm install -g surge
surge token
```

We’ve also put together a guide on [how to publish using Travis CI](https://surge.sh/help/integrating-with-travis-ci), I’d love to get your feedback on that. There’s also a [companion example repository](https://github.com/surge-sh/example-travisci).

This kind of setup should also work with other CI services too, but we’ll be writing more guides soon.

**Comment by constantx** [comment]
:+1:

**Comment by kennethormandy** [comment]
:ship: [How to integrate Codeship](https://surge.sh/help/integrating-with-codeship) is now live. There’s [an example companion repo](https://github.com/surge-sh/example-codeship) for that as well.

I’ll probably write Wercker and CircleCI guides as well since they’ve been mentioned. Let us know if there’s anything others you’d like to see how to use `surge token` with.

**Comment by lukekarrys** [comment]
Thanks @kennethormandy! This is really great.

I don't think it's necessary to deploy from the test commands in codeship, since it is already getting deployed through the deployment pipeline. I opened a PR on the repo in case it is a mistake https://github.com/surge-sh/example-codeship/pull/1

**Comment by constantx** [comment]
just tried this today, and got `bash: line 1: surge: command not found` on circleCI

quite sure I have `surge` in my package.json though…

**Comment by constantx** [comment]
changed the path to `./node_modules/.bin/surge` fixed it… hmm, odd that it's not available on CircleCI machine

**Comment by kennethormandy** [comment]
@constantx Interesting, I didn’t have to do that in the example I made, but it’s possible something about the environment is different? Does that project happen to be open source? I can see if I can reproduce the problem.

**Comment by constantx** [comment]
just standard environment as far as I can tell. The `circle.yml` file is below:

```
deployment:
  production:
    branch: master
    commands:
      - grunt presurge
      - surge --project ./dist --domain mydomain.com
```

what's odd is `grunt` bin is in the PATH, but not `surge` :)

**Comment by kennethormandy** [comment]
@constantx I’ll investigate more, we might not be taking advantage of the `bin` listing in the `package.json` properly or something.

In the meantime, you could also make add the second command as an npm run script:

```
"deploy": "surge --project ./dist --domain mydomain.com"
```

…and update your `circle.yml` file to this:

```yml
deployment:
  production:
    branch: master
    commands:
      - grunt presurge
      - npm run deploy
```

Another alternative, since you’re already using Grunt, would be to use [grunt-surge](https://github.com/surge-sh/grunt-surge) directly.

Thanks for reporting that!

**Comment by constantx** [comment]
:+1: thanks @kennethormandy

**Comment by cfjedimaster** [comment]
surge token does not exist in surge -h - should it?

**Comment by jdsimcoe** [comment]
@marvinroger @kennethormandy to get Wercker working I had to add an environment variables for $SURGE_LOGIN to my Wercker project settings. Here's my `wercker.yml` for my Jekyll site:

```yaml
# our build should run within a Ruby box
build:
  box: phusion/passenger-ruby22
  steps:
    # Run a smart version of bundle install
    # which improves build execution time of
    # future builds
    - bundle-install

    # A custom script step
    # that actually builds the jekyll site
    - script:
      name: generate site
      code: bundle exec jekyll build --trace
    - script:
      name: copy build to the to-be-deployed directory
      code: cp -a ./. $WERCKER_OUTPUT_DIR

deploy:
  box: nodesource/trusty
  steps:
    - script:
      name: NPM install
      code: npm install -g surge
    - npm-test
    - script:
      name: push to Surge.sh
      code: surge _site/ <MYSITE>.surge.sh --token $SURGE_TOKEN
```

Works like a champ!
